### ISSUE TITLE
Missing bsapi headers?

### ISSUE THREAD

**Issue by shibotto** [hyperair/fprint-bsapi#1]
Running ./autogen.sh I get this

```
checking bsapi.h usability... no
checking bsapi.h presence... no
checking for bsapi.h... no
configure: error: Could not find libbsapi headers`
```

Is libbsapi supposed to be an external library? If yes, where can it be retrieved?

**Comment by hyperair** [comment]
Yeah it's an external, proprietary driver library provided by the vendor. I can't recall where I downloaded it from though.

**Comment by hyperair** [comment]
Oh there's a package in this PPA: https://launchpad.net/~fingerprint/+archive/ubuntu/fingerprint-gui/+packages, and the homepage listed there is http://www.upek.com/solutions/pc_and_networking/sdks/linux/

Edit: Looks like upek.com has been taken over by a domain squatter though.

**Comment by shibotto** [comment]
Ok, thank you. Having found a resource I think I can close the issue.
